// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerData } from "./tables/Player.sol";
import { Country, CountryData } from "./tables/Country.sol";
import { GlobalState, GlobalStateData } from "./tables/GlobalState.sol";
import { ClickSession, ClickSessionData } from "./tables/ClickSession.sol";
