// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct CountryData {
  uint256 totalClicks;
  uint32 playerCount;
  uint16 rank;
}

library Country {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "flowclicker", name: "Country", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462666c6f77636c69636b6572000000436f756e747279000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0026030020040200000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint32, uint16)
  Schema constant _valueSchema = Schema.wrap(0x002603001f030100000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "code";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "totalClicks";
    fieldNames[1] = "playerCount";
    fieldNames[2] = "rank";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get totalClicks.
   */
  function getTotalClicks(bytes32 code) internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalClicks.
   */
  function _getTotalClicks(bytes32 code) internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalClicks.
   */
  function setTotalClicks(bytes32 code, uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Set totalClicks.
   */
  function _setTotalClicks(bytes32 code, uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Get playerCount.
   */
  function getPlayerCount(bytes32 code) internal view returns (uint32 playerCount) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get playerCount.
   */
  function _getPlayerCount(bytes32 code) internal view returns (uint32 playerCount) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set playerCount.
   */
  function setPlayerCount(bytes32 code, uint32 playerCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((playerCount)), _fieldLayout);
  }

  /**
   * @notice Set playerCount.
   */
  function _setPlayerCount(bytes32 code, uint32 playerCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((playerCount)), _fieldLayout);
  }

  /**
   * @notice Get rank.
   */
  function getRank(bytes32 code) internal view returns (uint16 rank) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get rank.
   */
  function _getRank(bytes32 code) internal view returns (uint16 rank) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set rank.
   */
  function setRank(bytes32 code, uint16 rank) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((rank)), _fieldLayout);
  }

  /**
   * @notice Set rank.
   */
  function _setRank(bytes32 code, uint16 rank) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((rank)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 code) internal view returns (CountryData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 code) internal view returns (CountryData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 code, uint256 totalClicks, uint32 playerCount, uint16 rank) internal {
    bytes memory _staticData = encodeStatic(totalClicks, playerCount, rank);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 code, uint256 totalClicks, uint32 playerCount, uint16 rank) internal {
    bytes memory _staticData = encodeStatic(totalClicks, playerCount, rank);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 code, CountryData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.totalClicks, _table.playerCount, _table.rank);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 code, CountryData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.totalClicks, _table.playerCount, _table.rank);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 totalClicks, uint32 playerCount, uint16 rank) {
    totalClicks = (uint256(Bytes.getBytes32(_blob, 0)));

    playerCount = (uint32(Bytes.getBytes4(_blob, 32)));

    rank = (uint16(Bytes.getBytes2(_blob, 36)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (CountryData memory _table) {
    (_table.totalClicks, _table.playerCount, _table.rank) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 code) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 code) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 totalClicks, uint32 playerCount, uint16 rank) internal pure returns (bytes memory) {
    return abi.encodePacked(totalClicks, playerCount, rank);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 totalClicks,
    uint32 playerCount,
    uint16 rank
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(totalClicks, playerCount, rank);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 code) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = code;

    return _keyTuple;
  }
}
