// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GlobalStateData {
  uint256 totalClicks;
  uint32 totalPlayers;
  uint64 startTimestamp;
  uint256 currentRewardRate;
  uint256 totalRewardsDistributed;
}

library GlobalState {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "flowclicker", name: "GlobalState", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462666c6f77636c69636b6572000000476c6f62616c53746174650000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x006c050020040820200000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint32, uint64, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x006c05001f03071f1f0000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "totalClicks";
    fieldNames[1] = "totalPlayers";
    fieldNames[2] = "startTimestamp";
    fieldNames[3] = "currentRewardRate";
    fieldNames[4] = "totalRewardsDistributed";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get totalClicks.
   */
  function getTotalClicks() internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalClicks.
   */
  function _getTotalClicks() internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalClicks.
   */
  function setTotalClicks(uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Set totalClicks.
   */
  function _setTotalClicks(uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Get totalPlayers.
   */
  function getTotalPlayers() internal view returns (uint32 totalPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get totalPlayers.
   */
  function _getTotalPlayers() internal view returns (uint32 totalPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set totalPlayers.
   */
  function setTotalPlayers(uint32 totalPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((totalPlayers)), _fieldLayout);
  }

  /**
   * @notice Set totalPlayers.
   */
  function _setTotalPlayers(uint32 totalPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((totalPlayers)), _fieldLayout);
  }

  /**
   * @notice Get startTimestamp.
   */
  function getStartTimestamp() internal view returns (uint64 startTimestamp) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get startTimestamp.
   */
  function _getStartTimestamp() internal view returns (uint64 startTimestamp) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set startTimestamp.
   */
  function setStartTimestamp(uint64 startTimestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((startTimestamp)), _fieldLayout);
  }

  /**
   * @notice Set startTimestamp.
   */
  function _setStartTimestamp(uint64 startTimestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((startTimestamp)), _fieldLayout);
  }

  /**
   * @notice Get currentRewardRate.
   */
  function getCurrentRewardRate() internal view returns (uint256 currentRewardRate) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get currentRewardRate.
   */
  function _getCurrentRewardRate() internal view returns (uint256 currentRewardRate) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set currentRewardRate.
   */
  function setCurrentRewardRate(uint256 currentRewardRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((currentRewardRate)), _fieldLayout);
  }

  /**
   * @notice Set currentRewardRate.
   */
  function _setCurrentRewardRate(uint256 currentRewardRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((currentRewardRate)), _fieldLayout);
  }

  /**
   * @notice Get totalRewardsDistributed.
   */
  function getTotalRewardsDistributed() internal view returns (uint256 totalRewardsDistributed) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalRewardsDistributed.
   */
  function _getTotalRewardsDistributed() internal view returns (uint256 totalRewardsDistributed) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalRewardsDistributed.
   */
  function setTotalRewardsDistributed(uint256 totalRewardsDistributed) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((totalRewardsDistributed)), _fieldLayout);
  }

  /**
   * @notice Set totalRewardsDistributed.
   */
  function _setTotalRewardsDistributed(uint256 totalRewardsDistributed) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((totalRewardsDistributed)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GlobalStateData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GlobalStateData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 totalClicks,
    uint32 totalPlayers,
    uint64 startTimestamp,
    uint256 currentRewardRate,
    uint256 totalRewardsDistributed
  ) internal {
    bytes memory _staticData = encodeStatic(
      totalClicks,
      totalPlayers,
      startTimestamp,
      currentRewardRate,
      totalRewardsDistributed
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 totalClicks,
    uint32 totalPlayers,
    uint64 startTimestamp,
    uint256 currentRewardRate,
    uint256 totalRewardsDistributed
  ) internal {
    bytes memory _staticData = encodeStatic(
      totalClicks,
      totalPlayers,
      startTimestamp,
      currentRewardRate,
      totalRewardsDistributed
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GlobalStateData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.totalClicks,
      _table.totalPlayers,
      _table.startTimestamp,
      _table.currentRewardRate,
      _table.totalRewardsDistributed
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GlobalStateData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.totalClicks,
      _table.totalPlayers,
      _table.startTimestamp,
      _table.currentRewardRate,
      _table.totalRewardsDistributed
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 totalClicks,
      uint32 totalPlayers,
      uint64 startTimestamp,
      uint256 currentRewardRate,
      uint256 totalRewardsDistributed
    )
  {
    totalClicks = (uint256(Bytes.getBytes32(_blob, 0)));

    totalPlayers = (uint32(Bytes.getBytes4(_blob, 32)));

    startTimestamp = (uint64(Bytes.getBytes8(_blob, 36)));

    currentRewardRate = (uint256(Bytes.getBytes32(_blob, 44)));

    totalRewardsDistributed = (uint256(Bytes.getBytes32(_blob, 76)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GlobalStateData memory _table) {
    (
      _table.totalClicks,
      _table.totalPlayers,
      _table.startTimestamp,
      _table.currentRewardRate,
      _table.totalRewardsDistributed
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 totalClicks,
    uint32 totalPlayers,
    uint64 startTimestamp,
    uint256 currentRewardRate,
    uint256 totalRewardsDistributed
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(totalClicks, totalPlayers, startTimestamp, currentRewardRate, totalRewardsDistributed);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 totalClicks,
    uint32 totalPlayers,
    uint64 startTimestamp,
    uint256 currentRewardRate,
    uint256 totalRewardsDistributed
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      totalClicks,
      totalPlayers,
      startTimestamp,
      currentRewardRate,
      totalRewardsDistributed
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
