// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct PlayerData {
  uint256 totalClicks;
  uint256 totalRewards;
  bytes32 countryCode;
  uint64 lastClickTimestamp;
  uint16 trustScore;
  uint8 sequentialMaxClicks;
  bool isBotFlagged;
}

library Player {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "flowclicker", name: "Player", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462666c6f77636c69636b6572000000506c6179657200000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x006c070020202008020101000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (address)
  Schema constant _keySchema = Schema.wrap(0x0014010061000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, bytes32, uint64, uint16, uint8, bool)
  Schema constant _valueSchema = Schema.wrap(0x006c07001f1f5f07010060000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "player";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](7);
    fieldNames[0] = "totalClicks";
    fieldNames[1] = "totalRewards";
    fieldNames[2] = "countryCode";
    fieldNames[3] = "lastClickTimestamp";
    fieldNames[4] = "trustScore";
    fieldNames[5] = "sequentialMaxClicks";
    fieldNames[6] = "isBotFlagged";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get totalClicks.
   */
  function getTotalClicks(address player) internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalClicks.
   */
  function _getTotalClicks(address player) internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalClicks.
   */
  function setTotalClicks(address player, uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Set totalClicks.
   */
  function _setTotalClicks(address player, uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Get totalRewards.
   */
  function getTotalRewards(address player) internal view returns (uint256 totalRewards) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalRewards.
   */
  function _getTotalRewards(address player) internal view returns (uint256 totalRewards) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalRewards.
   */
  function setTotalRewards(address player, uint256 totalRewards) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((totalRewards)), _fieldLayout);
  }

  /**
   * @notice Set totalRewards.
   */
  function _setTotalRewards(address player, uint256 totalRewards) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((totalRewards)), _fieldLayout);
  }

  /**
   * @notice Get countryCode.
   */
  function getCountryCode(address player) internal view returns (bytes32 countryCode) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get countryCode.
   */
  function _getCountryCode(address player) internal view returns (bytes32 countryCode) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set countryCode.
   */
  function setCountryCode(address player, bytes32 countryCode) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((countryCode)), _fieldLayout);
  }

  /**
   * @notice Set countryCode.
   */
  function _setCountryCode(address player, bytes32 countryCode) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((countryCode)), _fieldLayout);
  }

  /**
   * @notice Get lastClickTimestamp.
   */
  function getLastClickTimestamp(address player) internal view returns (uint64 lastClickTimestamp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get lastClickTimestamp.
   */
  function _getLastClickTimestamp(address player) internal view returns (uint64 lastClickTimestamp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set lastClickTimestamp.
   */
  function setLastClickTimestamp(address player, uint64 lastClickTimestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((lastClickTimestamp)), _fieldLayout);
  }

  /**
   * @notice Set lastClickTimestamp.
   */
  function _setLastClickTimestamp(address player, uint64 lastClickTimestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((lastClickTimestamp)), _fieldLayout);
  }

  /**
   * @notice Get trustScore.
   */
  function getTrustScore(address player) internal view returns (uint16 trustScore) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get trustScore.
   */
  function _getTrustScore(address player) internal view returns (uint16 trustScore) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set trustScore.
   */
  function setTrustScore(address player, uint16 trustScore) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((trustScore)), _fieldLayout);
  }

  /**
   * @notice Set trustScore.
   */
  function _setTrustScore(address player, uint16 trustScore) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((trustScore)), _fieldLayout);
  }

  /**
   * @notice Get sequentialMaxClicks.
   */
  function getSequentialMaxClicks(address player) internal view returns (uint8 sequentialMaxClicks) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get sequentialMaxClicks.
   */
  function _getSequentialMaxClicks(address player) internal view returns (uint8 sequentialMaxClicks) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set sequentialMaxClicks.
   */
  function setSequentialMaxClicks(address player, uint8 sequentialMaxClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((sequentialMaxClicks)), _fieldLayout);
  }

  /**
   * @notice Set sequentialMaxClicks.
   */
  function _setSequentialMaxClicks(address player, uint8 sequentialMaxClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((sequentialMaxClicks)), _fieldLayout);
  }

  /**
   * @notice Get isBotFlagged.
   */
  function getIsBotFlagged(address player) internal view returns (bool isBotFlagged) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get isBotFlagged.
   */
  function _getIsBotFlagged(address player) internal view returns (bool isBotFlagged) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set isBotFlagged.
   */
  function setIsBotFlagged(address player, bool isBotFlagged) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((isBotFlagged)), _fieldLayout);
  }

  /**
   * @notice Set isBotFlagged.
   */
  function _setIsBotFlagged(address player, bool isBotFlagged) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((isBotFlagged)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(address player) internal view returns (PlayerData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(address player) internal view returns (PlayerData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address player,
    uint256 totalClicks,
    uint256 totalRewards,
    bytes32 countryCode,
    uint64 lastClickTimestamp,
    uint16 trustScore,
    uint8 sequentialMaxClicks,
    bool isBotFlagged
  ) internal {
    bytes memory _staticData = encodeStatic(
      totalClicks,
      totalRewards,
      countryCode,
      lastClickTimestamp,
      trustScore,
      sequentialMaxClicks,
      isBotFlagged
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address player,
    uint256 totalClicks,
    uint256 totalRewards,
    bytes32 countryCode,
    uint64 lastClickTimestamp,
    uint16 trustScore,
    uint8 sequentialMaxClicks,
    bool isBotFlagged
  ) internal {
    bytes memory _staticData = encodeStatic(
      totalClicks,
      totalRewards,
      countryCode,
      lastClickTimestamp,
      trustScore,
      sequentialMaxClicks,
      isBotFlagged
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(address player, PlayerData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.totalClicks,
      _table.totalRewards,
      _table.countryCode,
      _table.lastClickTimestamp,
      _table.trustScore,
      _table.sequentialMaxClicks,
      _table.isBotFlagged
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(address player, PlayerData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.totalClicks,
      _table.totalRewards,
      _table.countryCode,
      _table.lastClickTimestamp,
      _table.trustScore,
      _table.sequentialMaxClicks,
      _table.isBotFlagged
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 totalClicks,
      uint256 totalRewards,
      bytes32 countryCode,
      uint64 lastClickTimestamp,
      uint16 trustScore,
      uint8 sequentialMaxClicks,
      bool isBotFlagged
    )
  {
    totalClicks = (uint256(Bytes.getBytes32(_blob, 0)));

    totalRewards = (uint256(Bytes.getBytes32(_blob, 32)));

    countryCode = (Bytes.getBytes32(_blob, 64));

    lastClickTimestamp = (uint64(Bytes.getBytes8(_blob, 96)));

    trustScore = (uint16(Bytes.getBytes2(_blob, 104)));

    sequentialMaxClicks = (uint8(Bytes.getBytes1(_blob, 106)));

    isBotFlagged = (_toBool(uint8(Bytes.getBytes1(_blob, 107))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (PlayerData memory _table) {
    (
      _table.totalClicks,
      _table.totalRewards,
      _table.countryCode,
      _table.lastClickTimestamp,
      _table.trustScore,
      _table.sequentialMaxClicks,
      _table.isBotFlagged
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(address player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(address player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 totalClicks,
    uint256 totalRewards,
    bytes32 countryCode,
    uint64 lastClickTimestamp,
    uint16 trustScore,
    uint8 sequentialMaxClicks,
    bool isBotFlagged
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        totalClicks,
        totalRewards,
        countryCode,
        lastClickTimestamp,
        trustScore,
        sequentialMaxClicks,
        isBotFlagged
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 totalClicks,
    uint256 totalRewards,
    bytes32 countryCode,
    uint64 lastClickTimestamp,
    uint16 trustScore,
    uint8 sequentialMaxClicks,
    bool isBotFlagged
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      totalClicks,
      totalRewards,
      countryCode,
      lastClickTimestamp,
      trustScore,
      sequentialMaxClicks,
      isBotFlagged
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address player) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(uint160(player)));

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
