// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PlayerData } from "../tables/Player.sol";
import { CountryData } from "../tables/Country.sol";
import { GlobalStateData } from "../tables/GlobalState.sol";
import { ClickSessionData } from "../tables/ClickSession.sol";

/**
 * @title IClickSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClickSystem {
  error BotFlagged(address player);
  error RateLimitExceeded(address player, uint256 clicksInWindow);
  error InvalidCountryCode(bytes32 code);

  function flowclicker__initialize(address _flowToken) external;

  function flowclicker__click(bytes32 countryCode, uint256 clientTimestamp) external returns (uint256 tokensMinted);

  function flowclicker__getPlayer(address player) external view returns (PlayerData memory);

  function flowclicker__getCountry(bytes32 countryCode) external view returns (CountryData memory);

  function flowclicker__getGlobalState() external view returns (GlobalStateData memory);

  function flowclicker__getCurrentSession(address player) external view returns (ClickSessionData memory);
}
